import 'package:atmega/model/chapter.dart';

class Consts {
  static String title = "ATmega Erode";

static List<Chapter> chapters = [
  Chapter(
    title: "Flutter",
    topics: [
       "Flutter Hello World and Dart Syntax",
  "Understanding Flutter Widgets",
  "Layouts and UI Design",
  "Navigation and Routing",
  "State Management",
  "Fetching Data",
  "Working with Forms",
  "Persistence",
  "Animations and Custom Widgets",
  "Testing and Debugging",
  "Deployment and App Store",
  "Advanced Topics",
  "Community Packages and Plugins",
  "Continuous Learning and Updates",
  "Building Real-World Projects",
    ],
  ),
  Chapter(
    title: "React.js",
    topics: [
      "React Basics",
      "Component Lifecycle",
      "State and Props",
      "React Router",
      "Redux",
      "Hooks",
      "Forms and Validation",
      "Styling in React",
      "API Integration",
      "Testing in React",
      "React Native",
      "Performance Optimization",
      "Server-Side Rendering",
    ],
  ),
  Chapter(
    title: "Go Lang",
    topics: [
      "Go Basics",
      "Data Types and Variables",
      "Functions and Methods",
      "Packages and Modules",
      "Error Handling",
      "Concurrency in Go",
      "Web Development with Go",
      "Database Interaction",
      "RESTful APIs in Go",
      "Unit Testing in Go",
      "Building CLI Applications",
      "Distributed Systems with Go",
      "Go Best Practices",
      "Deployment and Scaling",
    ],
  ),
  Chapter(
    title: "Django",
    topics: [
      "Django Basics",
      "Models and Databases",
      "Views and Templates",
      "Forms and Validation",
      "Authentication and Authorization",
      "Django REST framework",
      "File Uploads",
      "Middleware",
      "Testing in Django",
      "Django Channels",
      "Caching",
      "Internationalization",
      "Deployment and Hosting",
    ],
  ),
  Chapter(
    title: "Flask",
    topics: [
      "Flask Basics",
      "Routing and Views",
      "Templates and Forms",
      "Database Integration",
      "RESTful APIs in Flask",
      "Authentication and Authorization",
      "Testing in Flask",
      "Deployment and Scaling",
    ],
  ),
  Chapter(
    title: "PHP",
    topics: [
      "PHP Basics",
      "Data Types and Variables",
      "Functions",
      "Database Integration",
      "Web Development with PHP",
      "Security in PHP",
      "PHP Frameworks",
    ],
  ),
  Chapter(
    title: "Laravel",
    topics: [
      "Laravel Basics",
      "Routing and Controllers",
      "Views and Blade Templates",
      "Eloquent ORM",
      "Authentication and Authorization",
      "API Development",
      "Testing in Laravel",
      "Laravel Deployment",
    ],
  ),
  Chapter(
    title: "Next.js",
    topics: [
      "Next.js Basics",
      "Server-Side Rendering",
      "Routing in Next.js",
      "API Routes",
      "Data Fetching",
      "Authentication in Next.js",
      "Styling in Next.js",
      "Testing in Next.js",
      "Deployment",
    ],
  ),
  Chapter(
    title: "Spring Boot",
    topics: [
      "Spring Boot Basics",
      "Spring MVC",
      "Spring Data JPA",
      "Spring Security",
      "RESTful APIs with Spring Boot",
      "Spring Boot Testing",
      "Microservices with Spring Boot",
      "Spring Boot Deployment",
    ],
  ),
  Chapter(
    title: "Android Studio",
    topics: [
      "Android Studio Basics",
      "Android App Components",
      "User Interface Design",
      "Activity Lifecycle",
      "Intents and Services",
      "Data Storage and Databases",
      "Networking in Android",
      "Testing and Debugging",
      "Publishing to Google Play",
    ],
  ),
  Chapter(
    title: "Java",
    topics: [
      "Java Basics",
      "Object-Oriented Programming",
      "Java Collections",
      "Multithreading in Java",
      "Exception Handling",
      "File I/O",
      "GUI Programming",
      "JavaFX",
      "Java Web Development",
    ],
  ),
  Chapter(
    title: "Python",
    topics: [
      "Python Basics",
      "Data Types and Variables",
      "Functions and Modules",
      "File Handling",
      "Object-Oriented Programming in Python",
      "Web Scraping with Python",
      "Data Analysis with Python",
      "Python Web Frameworks",
    ],
  ),
  Chapter(
    title: "C",
    topics: [
      "C Basics",
      "Data Types and Variables",
      "Functions and Pointers",
      "Arrays and Strings in C",
      "File Handling in C",
      "Memory Management",
      "Data Structures in C",
    ],
  ),
  Chapter(
    title: "C++",
    topics: [
      "C++ Basics",
      "Object-Oriented Programming in C++",
      "STL (Standard Template Library)",
      "Templates and Exception Handling",
      "File Handling in C++",
      "Concurrency in C++",
      "C++ GUI Programming",
    ],
  ),
];



  
}